<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chooseMale</name>
   <tag></tag>
   <elementGuidId>b5b2b5e1-8203-42de-aa38-cfdc598f0aab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//label[normalize-space()='Male'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label[normalize-space()='Male'])[1]</value>
      <webElementGuid>5c84fdb3-1c5a-43b0-a73f-a056974c7c45</webElementGuid>
   </webElementProperties>
</WebElementEntity>
